name: Deploy

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '* * * * *'
env:
  TZ: 'Asia/Singapore'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Schedule test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "heyethereum"
        git pull origin main
        echo "List of files in the directory:$(pwd)"
        ls -la
        p=$(date +%Y)/$(date +%m)/$(date +%d)/$(date +%H)
        mkdir -p $p
        out=$p/$(date +%s).txt
        curl "http://api.open-notify.org/iss-now.json" > $out
        echo $out
        git add -A
        git commit -m "changed $(date +%s)"
        git push origin main
        
